"""empty message

Revision ID: 1c328b2d2934
Revises: 
Create Date: 2023-03-30 15:42:38.293840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c328b2d2934'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_hotspot_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_plan_template', sa.String(length=255), nullable=False))
        batch_op.drop_constraint('template_hotspot_plan_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'plan_template', ['id_plan_template'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('id_template_plan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_hotspot_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_template_plan', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('template_hotspot_plan_ibfk_2', 'plan_template', ['id_template_plan'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('id_plan_template')

    # ### end Alembic commands ###
