"""empty message

Revision ID: ba9044cad28f
Revises: 
Create Date: 2023-03-24 11:16:57.479531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba9044cad28f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_default', schema=None) as batch_op:
        batch_op.drop_index('id')
        batch_op.drop_index('name')

    op.drop_table('plan_default')
    with op.batch_alter_table('plan_site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_id', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'plan_template', ['template_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_site', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('template_id')

    op.create_table('plan_default',
    sa.Column('id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('uptime', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('expired', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('kuota', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('limit_shared', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['plan_type.id'], name='plan_default_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('plan_default', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)
        batch_op.create_index('id', ['id'], unique=False)

    # ### end Alembic commands ###
